add caviar staking strategy
tetu-io/tetu-strategies-matic pull request #28
Opened 2023-08-29 22:22 UTC by AlehNat

2023-08-29 22:23 UTC, AlehNat commented on contracts/strategies/tangible/CaviarStakingStrategyBase.sol
> +        if (toGov != 0) {
@belbix Per my understanding (from the latest balancer strategies)  we are not using buybacks anymore. Please confirm.

2023-08-29 22:26 UTC, AlehNat commented on contracts/strategies/tangible/CaviarStakingStrategyBase.sol
> +    rewardTokens_[0] = USDR_TOKEN;
@belbix Here is a caveat.  According to the CAVIAR_CHEF there is an only one reward token - wURSD, but harvest sends USDR and CAVIAR tokens.  I decided to use only USDR as reward token. Not sure if it is correct.

2023-08-29 22:27 UTC, AlehNat commented on contracts/strategies/tangible/CaviarStakingStrategyBase.sol
> +  function setRewardTokens(address[] memory rts) external restricted {
I decided to include this method since Tangible is famous for upgrading it's tokens USDR is v3. There is a high probability that reward tokens will be updated.

2023-08-30 03:33 UTC, belbix commented on contracts/strategies/tangible/CaviarStakingStrategyBase.sol
> +        if (toGov != 0) {
yes, just send rewards directly

2023-08-30 08:16 UTC, belbix requested changes

2023-08-30 08:16 UTC, belbix commented on contracts/strategies/tangible/CaviarStakingStrategyBase.sol
> +    _liquidateRewards(silently, undBalanceBefore);
do we need liquidate if no tokens? better to move this into the if statement

2023-08-30 08:16 UTC, belbix commented on contracts/strategies/tangible/CaviarStakingStrategyBase.sol
> +    uint undBalanceBefore = IERC20(_underlying()).balanceOf(address(this));
why do you need this here?

2023-08-30 08:16 UTC, belbix commented on contracts/strategies/tangible/CaviarStakingStrategyBase.sol
> +          _liquidate(rt, _underlying(), toCompound, silently);
read slots in a loop not so good

2023-08-30 08:16 UTC, belbix commented on contracts/strategies/tangible/CaviarStakingStrategyBase.sol
> +    uint undBalance = IERC20(_underlying()).balanceOf(address(this)) - undBalBeforeHarvest;
reuse underlying

2023-08-30 08:16 UTC, belbix commented on contracts/strategies/tangible/CaviarStakingStrategyBase.sol
> +  uint256[45] private ______gap;
use 50 - count of variables (it's zero here)

2023-08-30 22:04 UTC, AlehNat commented on contracts/strategies/tangible/CaviarStakingStrategyBase.sol
> +    uint undBalanceBefore = IERC20(_underlying()).balanceOf(address(this));
We need to store amount of underlying (CAVIAR) before harvest to liquidate only harvested CAVIAR tokens.

2023-08-30 22:27 UTC, AlehNat commented on contracts/strategies/tangible/CaviarStakingStrategyBase.sol
> +    _liquidateRewards(silently, undBalanceBefore);
In case of withdrawAndClaimFromPool we are calling CAVIAR_CHEF.withdrawAndHarvest, we will have rewards which needs to be liquidated.

2023-08-30 22:30 UTC, AlehNat commented on contracts/strategies/tangible/CaviarStakingStrategyBase.sol
> +          _liquidate(rt, _underlying(), toCompound, silently);
fixed

2023-09-05 06:17 UTC, merged